/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface Cart {
  courseId: number;
  createdAt: Date;
  id?: number;
  price: number;
  userId: number;
}
export interface CourseObjective {
  courseId: number;
  id?: number;
  objective: string | null;
}
export interface Course {
  author: string;
  category: string;
  id?: number;
  price: number;
  rating?: number;
  subtitle: string | null;
  thumbUrl: string | null;
  title: string;
}
export interface EnrollProgress {
  enrollmentId: string;
  id?: string;
  lessonId: string;
}
export interface Enrollment {
  courseId: number;
  createdAt: Date;
  id?: string;
  isCompleted?: boolean;
  nextPosition?: number | null;
  progress?: number;
  updatedAt: Date | null;
  userId: number;
}
export interface Lesson {
  courseId: number;
  id: string;
  lengthSeconds?: number;
  lessonName: string;
  position: number;
  videokey: string;
}
export interface OrderItem {
  courseId: number;
  id?: string;
  transactionId: string;
}
export interface Review {
  content: string;
  courseId: number;
  createdAt: Date;
  id?: number;
  rating: number;
  updatedAt: Date | null;
  userId: number;
}
export interface Sale {
  createdAt: Date;
  paymentMethod: string;
  totalPaid: number;
  transactionId: string;
  userId: number;
}
export interface User {
  authProvider?: any;
  createdAt: Date;
  email: string;
  confirmPass?: string;
  fullname: string;
  id?: number;
  password: string | null;
  userRole?: any;
}
export interface Wishlist {
  courseId: number;
  createdAt: Date;
  id?: number;
  userId: number;
}
